---
#  url: "wss://mainnet.infura.io:443/ws"
  url: "ws://localhost:8647/"

  contractAddress: ''
  contractOwner: ''

  # the block the web3Contract was deplyed in.
  # This defaults to 0 if not set which makes getting the web3Contract events slower as it has to scan the whole blockchain
  contractAddressBlock:

  symbol: 'DAD'
  tokenName: 'Digital Australian Dollar Token'
